project_id = "codkpccwtffhoacwswso"

[functions.generate-weather-phrase]
verify_jwt = false

[functions.chat]
enabled = true
verify_jwt = false

[functions.transcribe-audio]
enabled = true
verify_jwt = false

[functions.analyze-image]
enabled = true
verify_jwt = false

[functions.text-to-speech]
enabled = true
verify_jwt = false

[functions.send-push-notification]
enabled = true
verify_jwt = false

[functions.check-upcoming-alerts]
enabled = true
verify_jwt = false

[functions.send-voip-push]
enabled = true
verify_jwt = false

[functions.generate-weekly-report]
enabled = true
verify_jwt = false

[functions.send-weekly-reports]
enabled = true
verify_jwt = false

[functions.get-weather-forecast]
enabled = true
verify_jwt = false

[functions.send-weather-forecasts]
enabled = true
verify_jwt = false

[functions.remote-log]
enabled = true
verify_jwt = false
